server:
    port: 8082
    #Notice that contextPath is mondary, other wise, you will get CSRF error
    #https://github.com/spring-projects/spring-security-oauth/issues/322
    contextPath: /resource
        
security:
    oauth2:
        resource:
#            token-info-uri: http://localhost:8081/oauth/check_token
            jwt:
                # Tells the JWT framework to fetch the public key from the authorization server during startup
                # Note: The authorization server needs to be running...
                key-uri: http://localhost:8081/oauth/token_key
                
                

